//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsterixDisplayAnalyser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Waypoints {
            get {
                return ((bool)(this["Waypoints"]));
            }
            set {
                this["Waypoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StateBorder {
            get {
                return ((bool)(this["StateBorder"]));
            }
            set {
                this["StateBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sectors {
            get {
                return ((bool)(this["Sectors"]));
            }
            set {
                this["Sectors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Radars {
            get {
                return ((bool)(this["Radars"]));
            }
            set {
                this["Radars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CAT_001_Enabled {
            get {
                return ((bool)(this["CAT_001_Enabled"]));
            }
            set {
                this["CAT_001_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CAT_002_Enabled {
            get {
                return ((bool)(this["CAT_002_Enabled"]));
            }
            set {
                this["CAT_002_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CAT_008_Enabled {
            get {
                return ((bool)(this["CAT_008_Enabled"]));
            }
            set {
                this["CAT_008_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CAT_034_Enabled {
            get {
                return ((bool)(this["CAT_034_Enabled"]));
            }
            set {
                this["CAT_034_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CAT_048_Enabled {
            get {
                return ((bool)(this["CAT_048_Enabled"]));
            }
            set {
                this["CAT_048_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CAT_062_Enabled {
            get {
                return ((bool)(this["CAT_062_Enabled"]));
            }
            set {
                this["CAT_062_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CAT_063_Enabled {
            get {
                return ((bool)(this["CAT_063_Enabled"]));
            }
            set {
                this["CAT_063_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CAT_065_Enabled {
            get {
                return ((bool)(this["CAT_065_Enabled"]));
            }
            set {
                this["CAT_065_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CAT_244_Enabled {
            get {
                return ((bool)(this["CAT_244_Enabled"]));
            }
            set {
                this["CAT_244_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int TrackCoast {
            get {
                return ((int)(this["TrackCoast"]));
            }
            set {
                this["TrackCoast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int UpdateRate {
            get {
                return ((int)(this["UpdateRate"]));
            }
            set {
                this["UpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayEnabled {
            get {
                return ((bool)(this["DisplayEnabled"]));
            }
            set {
                this["DisplayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FL_Filter_Enabled {
            get {
                return ((bool)(this["FL_Filter_Enabled"]));
            }
            set {
                this["FL_Filter_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FL_Upper {
            get {
                return ((decimal)(this["FL_Upper"]));
            }
            set {
                this["FL_Upper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public decimal FL_Lower {
            get {
                return ((decimal)(this["FL_Lower"]));
            }
            set {
                this["FL_Lower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayPSR {
            get {
                return ((bool)(this["DisplayPSR"]));
            }
            set {
                this["DisplayPSR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayModeC_As_FL {
            get {
                return ((bool)(this["DisplayModeC_As_FL"]));
            }
            set {
                this["DisplayModeC_As_FL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopulateMainListBox {
            get {
                return ((bool)(this["PopulateMainListBox"]));
            }
            set {
                this["PopulateMainListBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyncDisplayToNorthMark {
            get {
                return ((bool)(this["SyncDisplayToNorthMark"]));
            }
            set {
                this["SyncDisplayToNorthMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ASTERIX")]
        public string RecordingDirectory {
            get {
                return ((string)(this["RecordingDirectory"]));
            }
            set {
                this["RecordingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdInterface1 {
            get {
                return ((string)(this["FrwdInterface1"]));
            }
            set {
                this["FrwdInterface1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdInterface2 {
            get {
                return ((string)(this["FrwdInterface2"]));
            }
            set {
                this["FrwdInterface2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdInterface3 {
            get {
                return ((string)(this["FrwdInterface3"]));
            }
            set {
                this["FrwdInterface3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdInterface4 {
            get {
                return ((string)(this["FrwdInterface4"]));
            }
            set {
                this["FrwdInterface4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdInterface5 {
            get {
                return ((string)(this["FrwdInterface5"]));
            }
            set {
                this["FrwdInterface5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdMulticast1 {
            get {
                return ((string)(this["FrwdMulticast1"]));
            }
            set {
                this["FrwdMulticast1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdMulticast2 {
            get {
                return ((string)(this["FrwdMulticast2"]));
            }
            set {
                this["FrwdMulticast2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdMulticast3 {
            get {
                return ((string)(this["FrwdMulticast3"]));
            }
            set {
                this["FrwdMulticast3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdMulticast4 {
            get {
                return ((string)(this["FrwdMulticast4"]));
            }
            set {
                this["FrwdMulticast4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdMulticast5 {
            get {
                return ((string)(this["FrwdMulticast5"]));
            }
            set {
                this["FrwdMulticast5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdPort1 {
            get {
                return ((string)(this["FrwdPort1"]));
            }
            set {
                this["FrwdPort1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdPort2 {
            get {
                return ((string)(this["FrwdPort2"]));
            }
            set {
                this["FrwdPort2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdPort3 {
            get {
                return ((string)(this["FrwdPort3"]));
            }
            set {
                this["FrwdPort3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdPort4 {
            get {
                return ((string)(this["FrwdPort4"]));
            }
            set {
                this["FrwdPort4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FrwdPort5 {
            get {
                return ((string)(this["FrwdPort5"]));
            }
            set {
                this["FrwdPort5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GE_Show_ModeA {
            get {
                return ((bool)(this["GE_Show_ModeA"]));
            }
            set {
                this["GE_Show_ModeA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GE_Show_ModeC {
            get {
                return ((bool)(this["GE_Show_ModeC"]));
            }
            set {
                this["GE_Show_ModeC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GE_Show_Show_Callsign {
            get {
                return ((bool)(this["GE_Show_Show_Callsign"]));
            }
            set {
                this["GE_Show_Show_Callsign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_ModeC_as_FL {
            get {
                return ((bool)(this["Show_ModeC_as_FL"]));
            }
            set {
                this["Show_ModeC_as_FL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ASTERIX\\GE")]
        public string GE_Dest_Path {
            get {
                return ((string)(this["GE_Dest_Path"]));
            }
            set {
                this["GE_Dest_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecordActiveInRaw {
            get {
                return ((bool)(this["RecordActiveInRaw"]));
            }
            set {
                this["RecordActiveInRaw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReplayMulticast {
            get {
                return ((string)(this["ReplayMulticast"]));
            }
            set {
                this["ReplayMulticast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReplayPort {
            get {
                return ((string)(this["ReplayPort"]));
            }
            set {
                this["ReplayPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SystMonEnabled {
            get {
                return ((bool)(this["SystMonEnabled"]));
            }
            set {
                this["SystMonEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Runways {
            get {
                return ((bool)(this["Runways"]));
            }
            set {
                this["Runways"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayPosInDecimals {
            get {
                return ((bool)(this["DisplayPosInDecimals"]));
            }
            set {
                this["DisplayPosInDecimals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal SpeedVector {
            get {
                return ((decimal)(this["SpeedVector"]));
            }
            set {
                this["SpeedVector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal HistoryPoints {
            get {
                return ((decimal)(this["HistoryPoints"]));
            }
            set {
                this["HistoryPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SEepToolUpdateRate {
            get {
                return ((int)(this["SEepToolUpdateRate"]));
            }
            set {
                this["SEepToolUpdateRate"] = value;
            }
        }
    }
}
